 export const constants = {
	SERVER_PORT: 8610,
	SOCKET_ENDPOINT_PORT: 1990,
	BROADCAST_PORT: 1990,
	BROADCAST_ADDRESS: "255.255.255.255",
	OUTPUT_CHANGE: 'OUTPUT_CHANGE',
	EVENTS: {
		INITIAL: 'INITIAL',
		INPUT_CHANGE: 'INPUT_CHANGE',
		OUTPUT_CHANGE: 'OUTPUT_CHANGE'
	},
	LEVEL: {UP: 1 as 1, DOWN: 0 as 0}
};