export const CONSTANTS = {
    SERVER_PORT: 8610,
    SOCKET_ENDPOINT_PORT: 1990,
    BROADCAST_PORT: 1990,
    BROADCAST_ADDRESS: "255.255.255.255",
    INPUT_CHANGE: 'INPUT_CHANGE',
    EVENTS: {
        INITIAL: 'INITIAL',
        CHANGE: 'CHANGE'
    },
    LEVEL: {UP: 1, DOWN: 0}


};